[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Blue Ocean Client
- FILE
<pre>.</pre>

## Main Form

### Models
- FILE
<pre>src/MainForm/Models</pre>

#### UserModel
- FILE
<pre>src/MainForm/Models/UserModel.java</pre>

### Controllers
- FILE
<pre>src/MainForm/Controllers</pre>

#### FogottenPasswordController
- FILE
<pre>src/MainForm/Controllers/FogottenPasswordController.java</pre>

#### LoginController
- FILE
<pre>src/MainForm/Controllers/LogInController.java</pre>

#### RegistorController
- FILE
<pre>src/MainForm/Controllers/RegistorController.java</pre>

### Utils
- FILE
<pre>src/MainForm/Utils</pre>

#### AnimationFx
- FILE
<pre>src/MainForm/Utils/AnimationFx.java</pre>

#### DatabaseHelper
- FILE
<pre>src/MainForm/Utils/DatabaseHelper.java</pre>

#### checkInputData
- FILE
<pre>src/MainForm/Utils/checkInputData.java</pre>

### Views
- FILE
<pre>src/MainForm/Views</pre>

#### LoginView
- FILE
<pre>src/MainForm/Views/LogInView.java</pre>

#### RegistorView
- FILE
<pre>src/MainForm/Views/RegisterView.java</pre>

#### FogottenPasswordView
- FILE
<pre>src/MainForm/Views/ForgottenPasswordView.java</pre>

### Main
- FILE
<pre>src/MainForm/Main.java</pre>

### TermsandLicense
- FILE
<pre>src/MainForm/TermsandLicense.java</pre>

## Blue Ocean Scene
> leftSide=`true`

- FILE
<pre>src/BlueOceanScene</pre>

### Main Scene

## Chat App
> leftSide=`true`

- FILE
<pre>src/ChatApp</pre>

### Main Scene
