[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Blue Ocean Client
- FILE
<pre>.</pre>

## Main Form

### Models
- FILE
<pre>src/MainForm/Models</pre>

#### UserModel
- FILE
<pre>src/MainForm/Models/UserModel.java</pre>

#### HelpQuickLogin
- FILE
<pre>src/MainForm/Models/HelpQuickLogin.java</pre>

#### UserTemps
- FILE
<pre>src/MainForm/Models/UserTemps.java</pre>

### Controllers
- FILE
<pre>src/MainForm/Controllers</pre>

#### FogottenPasswordController
- FILE
<pre>src/MainForm/Controllers/FogottenPasswordController.java</pre>

#### LoginController
- FILE
<pre>src/MainForm/Controllers/LogInController.java</pre>

#### RegistorController
- FILE
<pre>src/MainForm/Controllers/RegistorController.java</pre>

### Utils
- FILE
<pre>src/MainForm/Utils</pre>

#### AnimationFx
- FILE
<pre>src/MainForm/Utils/AnimationFx.java</pre>

#### DatabaseHelper
- FILE
<pre>src/MainForm/Utils/DatabaseHelper.java</pre>

#### checkInputData
- FILE
<pre>src/MainForm/Utils/checkInputData.java</pre>

#### QuickLogin
- FILE
<pre>src/MainForm/Utils/QuickLogin.java</pre>

### Views
- FILE
<pre>src/MainForm/Views</pre>

#### LoginView
- FILE
<pre>src/MainForm/Views/LogInView.java</pre>

#### RegistorView
- FILE
<pre>src/MainForm/Views/RegisterView.java</pre>

#### FogottenPasswordView
- FILE
<pre>src/MainForm/Views/ForgottenPasswordView.java</pre>

### Main
- FILE
<pre>src/MainForm/Main.java</pre>

### TermsandLicense
- FILE
<pre>src/MainForm/TermsandLicense.java</pre>

## Blue Ocean Scene
> leftSide=`true`

- FILE
<pre>src/BlueOceanScene</pre>

### View
- FILE
<pre>src/BlueOceanScene/View</pre>

#### CalendarView
- FILE
<pre>src/BlueOceanScene/View/CalendarView.java</pre>

### Main
- FILE
<pre>src/BlueOceanScene/Main.java</pre>

### Layout
- FILE
<pre>src/BlueOceanScene/Layouts</pre>

#### AppsLayout
- FILE
<pre>src/BlueOceanScene/Layouts/AppsLayout.java</pre>

#### InfoLayout
- FILE
<pre>src/BlueOceanScene/Layouts/InfoLayout.java</pre>

#### NewsLayout
- FILE
<pre>src/BlueOceanScene/Layouts/NewsLayout.java</pre>

#### ProfileLayout
- FILE
<pre>src/BlueOceanScene/Layouts/ProfileLayout.java</pre>

#### SettingLayout
- FILE
<pre>src/BlueOceanScene/Layouts/SettingLayout.java</pre>

### Models
- FILE
<pre>src/BlueOceanScene/Models</pre>

#### QuoteItem
- FILE
<pre>src/BlueOceanScene/Models/QuoteItem.java</pre>

#### Song
- FILE
<pre>src/BlueOceanScene/Models/Song.java</pre>

### Utils
- FILE
<pre>src/BlueOceanScene/Utils</pre>

#### AnimationFx
- FILE
<pre>src/BlueOceanScene/Utils/AnimationFx.java</pre>

#### MediaMusic
- FILE
<pre>src/BlueOceanScene/Utils/MediaMusic.java</pre>

#### QuoteSlideshow
- FILE
<pre>src/BlueOceanScene/Utils/QuoteSlideshow.java</pre>

#### ReminderPanel
- FILE
<pre>src/BlueOceanScene/Utils/ReminderPanel.java</pre>

### subApps
- FILE
<pre>src/BlueOceanScene/subApps</pre>

#### ListAppsIcon
- FILE
<pre>src/BlueOceanScene/subApps/ListAppsIcon.java</pre>

#### bgApps
- FILE
<pre>src/BlueOceanScene/subApps/bgApps.java</pre>

### subProfile
- FILE
<pre>src/BlueOceanScene/subProfile</pre>

#### previewSub
- FILE
<pre>src/BlueOceanScene/subProfile/previewSub.java</pre>

### subSetting
- FILE
<pre>src/BlueOceanScene/subSetting</pre>

#### LoginSetting
- FILE
<pre>src/BlueOceanScene/subSetting/LoginSetting.java</pre>

#### MuBackSetting
- FILE
<pre>src/BlueOceanScene/subSetting/MucBackSetting.java</pre>
